@echo off
echo Open Watcom Build Environment
SET PATH=C:\WATCOM19\BINW;%PATH%
SET INCLUDE=C:\WATCOM19\H;%INCLUDE%
SET WATCOM=C:\WATCOM19
SET EDPATH=C:\WATCOM19\EDDAT
SET WIPFC=C:\WATCOM19\WIPFC
